// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PendingActions.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PendingActionsResponse
    {
        /// <summary>
        /// Initializes a new instance of the PendingActionsResponse class.
        /// </summary>
        public PendingActionsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PendingActionsResponse class.
        /// </summary>
        public PendingActionsResponse(IList<string> pendingActions = default(IList<string>))
        {
            PendingActions = pendingActions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PendingActions")]
        public IList<string> PendingActions { get; set; }

    }
}
