// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PendingActions.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PendingActionType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PendingActionType
    {
        [EnumMember(Value = "UnsignedTransaction")]
        UnsignedTransaction,
        [EnumMember(Value = "OffchainRequest")]
        OffchainRequest,
        [EnumMember(Value = "ClientDialog")]
        ClientDialog
    }
    internal static class PendingActionTypeEnumExtension
    {
        internal static string ToSerializedValue(this PendingActionType? value)
        {
            return value == null ? null : ((PendingActionType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PendingActionType value)
        {
            switch( value )
            {
                case PendingActionType.UnsignedTransaction:
                    return "UnsignedTransaction";
                case PendingActionType.OffchainRequest:
                    return "OffchainRequest";
                case PendingActionType.ClientDialog:
                    return "ClientDialog";
            }
            return null;
        }

        internal static PendingActionType? ParsePendingActionType(this string value)
        {
            switch( value )
            {
                case "UnsignedTransaction":
                    return PendingActionType.UnsignedTransaction;
                case "OffchainRequest":
                    return PendingActionType.OffchainRequest;
                case "ClientDialog":
                    return PendingActionType.ClientDialog;
            }
            return null;
        }
    }
}
