// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PendingActions.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetPendingModel
    {
        /// <summary>
        /// Initializes a new instance of the SetPendingModel class.
        /// </summary>
        public SetPendingModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetPendingModel class.
        /// </summary>
        /// <param name="actionType">Possible values include:
        /// 'UnsignedTransaction', 'OffchainRequest', 'ClientDialog'</param>
        public SetPendingModel(PendingActionType actionType, bool pending, string clientId = default(string))
        {
            ClientId = clientId;
            ActionType = actionType;
            Pending = pending;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'UnsignedTransaction',
        /// 'OffchainRequest', 'ClientDialog'
        /// </summary>
        [JsonProperty(PropertyName = "ActionType")]
        public PendingActionType ActionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pending")]
        public bool Pending { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
